package com.test.dao;

import com.test.model.FeeConfig;

public interface FeeConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_FEE_CONFIG
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_FEE_CONFIG
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int insert(FeeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_FEE_CONFIG
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int insertSelective(FeeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_FEE_CONFIG
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    FeeConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_FEE_CONFIG
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int updateByPrimaryKeySelective(FeeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_FEE_CONFIG
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int updateByPrimaryKey(FeeConfig record);
}