package com.test.dao;

import com.test.model.PayConfig;

public interface PayConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_CONFIG
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_CONFIG
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int insert(PayConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_CONFIG
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int insertSelective(PayConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_CONFIG
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    PayConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_CONFIG
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int updateByPrimaryKeySelective(PayConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_CONFIG
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int updateByPrimaryKey(PayConfig record);
}