package com.test.dao;

import com.test.model.PayDict;

public interface PayDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_DICT
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int insert(PayDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_DICT
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int insertSelective(PayDict record);
}