package com.test.dao;

import com.test.model.PayOrderList;

public interface PayOrderListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_ORDER_LIST
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_ORDER_LIST
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int insert(PayOrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_ORDER_LIST
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int insertSelective(PayOrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_ORDER_LIST
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    PayOrderList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_ORDER_LIST
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int updateByPrimaryKeySelective(PayOrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_ORDER_LIST
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int updateByPrimaryKey(PayOrderList record);
}