package com.test.dao;

import com.test.model.PayOrderHistory;

public interface PayOrderHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_ORDER_HISTORY
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_ORDER_HISTORY
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int insert(PayOrderHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_ORDER_HISTORY
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int insertSelective(PayOrderHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_ORDER_HISTORY
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    PayOrderHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_ORDER_HISTORY
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int updateByPrimaryKeySelective(PayOrderHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_ORDER_HISTORY
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int updateByPrimaryKey(PayOrderHistory record);
}