package com.test.dao;

import com.test.model.PayRepaymentFail;

public interface PayRepaymentFailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_REPAYMENT_FAIL
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_REPAYMENT_FAIL
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int insert(PayRepaymentFail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_REPAYMENT_FAIL
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int insertSelective(PayRepaymentFail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_REPAYMENT_FAIL
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    PayRepaymentFail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_REPAYMENT_FAIL
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int updateByPrimaryKeySelective(PayRepaymentFail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_REPAYMENT_FAIL
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int updateByPrimaryKey(PayRepaymentFail record);
}