package com.test.dao;

import com.test.model.PaySysUser;

public interface PaySysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_SYS_USER
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_SYS_USER
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int insert(PaySysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_SYS_USER
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int insertSelective(PaySysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_SYS_USER
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    PaySysUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_SYS_USER
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int updateByPrimaryKeySelective(PaySysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UCARD_PAY_SYS_USER
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    int updateByPrimaryKey(PaySysUser record);
}