package com.test.model;

import java.math.BigDecimal;

public class FeeConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_FEE_CONFIG.ID
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_FEE_CONFIG.CONFIG_ID
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String configId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_FEE_CONFIG.REPAY_MIN
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private BigDecimal repayMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_FEE_CONFIG.REPAY_MAX
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private BigDecimal repayMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_FEE_CONFIG.FEES
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private Integer fees;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_FEE_CONFIG.FEES_MAX
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private BigDecimal feesMax;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_FEE_CONFIG.ID
     *
     * @return the value of UCARD_FEE_CONFIG.ID
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_FEE_CONFIG.ID
     *
     * @param id the value for UCARD_FEE_CONFIG.ID
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_FEE_CONFIG.CONFIG_ID
     *
     * @return the value of UCARD_FEE_CONFIG.CONFIG_ID
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_FEE_CONFIG.CONFIG_ID
     *
     * @param configId the value for UCARD_FEE_CONFIG.CONFIG_ID
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setConfigId(String configId) {
        this.configId = configId == null ? null : configId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_FEE_CONFIG.REPAY_MIN
     *
     * @return the value of UCARD_FEE_CONFIG.REPAY_MIN
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public BigDecimal getRepayMin() {
        return repayMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_FEE_CONFIG.REPAY_MIN
     *
     * @param repayMin the value for UCARD_FEE_CONFIG.REPAY_MIN
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setRepayMin(BigDecimal repayMin) {
        this.repayMin = repayMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_FEE_CONFIG.REPAY_MAX
     *
     * @return the value of UCARD_FEE_CONFIG.REPAY_MAX
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public BigDecimal getRepayMax() {
        return repayMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_FEE_CONFIG.REPAY_MAX
     *
     * @param repayMax the value for UCARD_FEE_CONFIG.REPAY_MAX
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setRepayMax(BigDecimal repayMax) {
        this.repayMax = repayMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_FEE_CONFIG.FEES
     *
     * @return the value of UCARD_FEE_CONFIG.FEES
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public Integer getFees() {
        return fees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_FEE_CONFIG.FEES
     *
     * @param fees the value for UCARD_FEE_CONFIG.FEES
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setFees(Integer fees) {
        this.fees = fees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_FEE_CONFIG.FEES_MAX
     *
     * @return the value of UCARD_FEE_CONFIG.FEES_MAX
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public BigDecimal getFeesMax() {
        return feesMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_FEE_CONFIG.FEES_MAX
     *
     * @param feesMax the value for UCARD_FEE_CONFIG.FEES_MAX
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setFeesMax(BigDecimal feesMax) {
        this.feesMax = feesMax;
    }
}