package com.test.model;

import java.util.Date;

public class PayConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_CONFIG.ID
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_CONFIG.PAY_CHANNEL
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String payChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_CONFIG.PAY_TYPE
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_CONFIG.PAY_WAY
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String payWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_CONFIG.STATUS
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_CONFIG.OPEN_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private Date openTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_CONFIG.CLOSE_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private Date closeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_CONFIG.CREATE_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_CONFIG.UPDATE_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_CONFIG.ID
     *
     * @return the value of UCARD_PAY_CONFIG.ID
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_CONFIG.ID
     *
     * @param id the value for UCARD_PAY_CONFIG.ID
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_CONFIG.PAY_CHANNEL
     *
     * @return the value of UCARD_PAY_CONFIG.PAY_CHANNEL
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getPayChannel() {
        return payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_CONFIG.PAY_CHANNEL
     *
     * @param payChannel the value for UCARD_PAY_CONFIG.PAY_CHANNEL
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setPayChannel(String payChannel) {
        this.payChannel = payChannel == null ? null : payChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_CONFIG.PAY_TYPE
     *
     * @return the value of UCARD_PAY_CONFIG.PAY_TYPE
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_CONFIG.PAY_TYPE
     *
     * @param payType the value for UCARD_PAY_CONFIG.PAY_TYPE
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_CONFIG.PAY_WAY
     *
     * @return the value of UCARD_PAY_CONFIG.PAY_WAY
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getPayWay() {
        return payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_CONFIG.PAY_WAY
     *
     * @param payWay the value for UCARD_PAY_CONFIG.PAY_WAY
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setPayWay(String payWay) {
        this.payWay = payWay == null ? null : payWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_CONFIG.STATUS
     *
     * @return the value of UCARD_PAY_CONFIG.STATUS
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_CONFIG.STATUS
     *
     * @param status the value for UCARD_PAY_CONFIG.STATUS
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_CONFIG.OPEN_TIME
     *
     * @return the value of UCARD_PAY_CONFIG.OPEN_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public Date getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_CONFIG.OPEN_TIME
     *
     * @param openTime the value for UCARD_PAY_CONFIG.OPEN_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_CONFIG.CLOSE_TIME
     *
     * @return the value of UCARD_PAY_CONFIG.CLOSE_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_CONFIG.CLOSE_TIME
     *
     * @param closeTime the value for UCARD_PAY_CONFIG.CLOSE_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_CONFIG.CREATE_TIME
     *
     * @return the value of UCARD_PAY_CONFIG.CREATE_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_CONFIG.CREATE_TIME
     *
     * @param createTime the value for UCARD_PAY_CONFIG.CREATE_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_CONFIG.UPDATE_TIME
     *
     * @return the value of UCARD_PAY_CONFIG.UPDATE_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_CONFIG.UPDATE_TIME
     *
     * @param updateTime the value for UCARD_PAY_CONFIG.UPDATE_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}