package com.test.model;

public class PayDict {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_DICT.DICT_TYPE
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String dictType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_DICT.DICT_DATA
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String dictData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_DICT.DICT_NAME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String dictName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_DICT.DICT_TYPE
     *
     * @return the value of UCARD_PAY_DICT.DICT_TYPE
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_DICT.DICT_TYPE
     *
     * @param dictType the value for UCARD_PAY_DICT.DICT_TYPE
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_DICT.DICT_DATA
     *
     * @return the value of UCARD_PAY_DICT.DICT_DATA
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getDictData() {
        return dictData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_DICT.DICT_DATA
     *
     * @param dictData the value for UCARD_PAY_DICT.DICT_DATA
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setDictData(String dictData) {
        this.dictData = dictData == null ? null : dictData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_DICT.DICT_NAME
     *
     * @return the value of UCARD_PAY_DICT.DICT_NAME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_DICT.DICT_NAME
     *
     * @param dictName the value for UCARD_PAY_DICT.DICT_NAME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }
}