package com.test.model;

import java.math.BigDecimal;
import java.util.Date;

public class PayOrderHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.ID
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.ID_TYP
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String idTyp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.ID_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String idNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.CUST_NAME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String custName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.REPAYMENT_METHOD
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String repaymentMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.LOAN_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String loanNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.ADVANCE_AMT
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String advanceAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.PAYMENT_ODER_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String paymentOderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.OUT_TRADE_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String outTradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.XD_FKDD_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String xdFkddNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.TRADE_TYPE
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String tradeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.ORDER_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.ORDER_STATUS
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.TIME_END
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private Date timeEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.CALLBACK_STATUS
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String callbackStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.CALLBACK_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private Date callbackTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.PREPAYMENT_POUNDAGE
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private BigDecimal prepaymentPoundage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.XD_REPAY_STATUS
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String xdRepayStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.LAST_POLLING_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private Date lastPollingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.POLLING_COUNT
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private Long pollingCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.OPENID
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.BANK_TYPE
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String bankType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_ORDER_HISTORY.COUPON_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String couponNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.ID
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.ID
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.ID
     *
     * @param id the value for UCARD_PAY_ORDER_HISTORY.ID
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.ID_TYP
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.ID_TYP
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getIdTyp() {
        return idTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.ID_TYP
     *
     * @param idTyp the value for UCARD_PAY_ORDER_HISTORY.ID_TYP
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setIdTyp(String idTyp) {
        this.idTyp = idTyp == null ? null : idTyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.ID_NO
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.ID_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.ID_NO
     *
     * @param idNo the value for UCARD_PAY_ORDER_HISTORY.ID_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.CUST_NAME
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.CUST_NAME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.CUST_NAME
     *
     * @param custName the value for UCARD_PAY_ORDER_HISTORY.CUST_NAME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.REPAYMENT_METHOD
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.REPAYMENT_METHOD
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getRepaymentMethod() {
        return repaymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.REPAYMENT_METHOD
     *
     * @param repaymentMethod the value for UCARD_PAY_ORDER_HISTORY.REPAYMENT_METHOD
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setRepaymentMethod(String repaymentMethod) {
        this.repaymentMethod = repaymentMethod == null ? null : repaymentMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.LOAN_NO
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.LOAN_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getLoanNo() {
        return loanNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.LOAN_NO
     *
     * @param loanNo the value for UCARD_PAY_ORDER_HISTORY.LOAN_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setLoanNo(String loanNo) {
        this.loanNo = loanNo == null ? null : loanNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.ADVANCE_AMT
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.ADVANCE_AMT
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getAdvanceAmt() {
        return advanceAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.ADVANCE_AMT
     *
     * @param advanceAmt the value for UCARD_PAY_ORDER_HISTORY.ADVANCE_AMT
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setAdvanceAmt(String advanceAmt) {
        this.advanceAmt = advanceAmt == null ? null : advanceAmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.PAYMENT_ODER_NO
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.PAYMENT_ODER_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getPaymentOderNo() {
        return paymentOderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.PAYMENT_ODER_NO
     *
     * @param paymentOderNo the value for UCARD_PAY_ORDER_HISTORY.PAYMENT_ODER_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setPaymentOderNo(String paymentOderNo) {
        this.paymentOderNo = paymentOderNo == null ? null : paymentOderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.OUT_TRADE_NO
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.OUT_TRADE_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.OUT_TRADE_NO
     *
     * @param outTradeNo the value for UCARD_PAY_ORDER_HISTORY.OUT_TRADE_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.XD_FKDD_NO
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.XD_FKDD_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getXdFkddNo() {
        return xdFkddNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.XD_FKDD_NO
     *
     * @param xdFkddNo the value for UCARD_PAY_ORDER_HISTORY.XD_FKDD_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setXdFkddNo(String xdFkddNo) {
        this.xdFkddNo = xdFkddNo == null ? null : xdFkddNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.TRADE_TYPE
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.TRADE_TYPE
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.TRADE_TYPE
     *
     * @param tradeType the value for UCARD_PAY_ORDER_HISTORY.TRADE_TYPE
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.ORDER_TIME
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.ORDER_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.ORDER_TIME
     *
     * @param orderTime the value for UCARD_PAY_ORDER_HISTORY.ORDER_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.ORDER_STATUS
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.ORDER_STATUS
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.ORDER_STATUS
     *
     * @param orderStatus the value for UCARD_PAY_ORDER_HISTORY.ORDER_STATUS
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.TIME_END
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.TIME_END
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public Date getTimeEnd() {
        return timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.TIME_END
     *
     * @param timeEnd the value for UCARD_PAY_ORDER_HISTORY.TIME_END
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setTimeEnd(Date timeEnd) {
        this.timeEnd = timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.CALLBACK_STATUS
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.CALLBACK_STATUS
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getCallbackStatus() {
        return callbackStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.CALLBACK_STATUS
     *
     * @param callbackStatus the value for UCARD_PAY_ORDER_HISTORY.CALLBACK_STATUS
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setCallbackStatus(String callbackStatus) {
        this.callbackStatus = callbackStatus == null ? null : callbackStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.CALLBACK_TIME
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.CALLBACK_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public Date getCallbackTime() {
        return callbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.CALLBACK_TIME
     *
     * @param callbackTime the value for UCARD_PAY_ORDER_HISTORY.CALLBACK_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setCallbackTime(Date callbackTime) {
        this.callbackTime = callbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.PREPAYMENT_POUNDAGE
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.PREPAYMENT_POUNDAGE
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public BigDecimal getPrepaymentPoundage() {
        return prepaymentPoundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.PREPAYMENT_POUNDAGE
     *
     * @param prepaymentPoundage the value for UCARD_PAY_ORDER_HISTORY.PREPAYMENT_POUNDAGE
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setPrepaymentPoundage(BigDecimal prepaymentPoundage) {
        this.prepaymentPoundage = prepaymentPoundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.XD_REPAY_STATUS
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.XD_REPAY_STATUS
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getXdRepayStatus() {
        return xdRepayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.XD_REPAY_STATUS
     *
     * @param xdRepayStatus the value for UCARD_PAY_ORDER_HISTORY.XD_REPAY_STATUS
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setXdRepayStatus(String xdRepayStatus) {
        this.xdRepayStatus = xdRepayStatus == null ? null : xdRepayStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.LAST_POLLING_TIME
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.LAST_POLLING_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public Date getLastPollingTime() {
        return lastPollingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.LAST_POLLING_TIME
     *
     * @param lastPollingTime the value for UCARD_PAY_ORDER_HISTORY.LAST_POLLING_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setLastPollingTime(Date lastPollingTime) {
        this.lastPollingTime = lastPollingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.POLLING_COUNT
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.POLLING_COUNT
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public Long getPollingCount() {
        return pollingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.POLLING_COUNT
     *
     * @param pollingCount the value for UCARD_PAY_ORDER_HISTORY.POLLING_COUNT
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setPollingCount(Long pollingCount) {
        this.pollingCount = pollingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.OPENID
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.OPENID
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.OPENID
     *
     * @param openid the value for UCARD_PAY_ORDER_HISTORY.OPENID
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.BANK_TYPE
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.BANK_TYPE
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getBankType() {
        return bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.BANK_TYPE
     *
     * @param bankType the value for UCARD_PAY_ORDER_HISTORY.BANK_TYPE
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setBankType(String bankType) {
        this.bankType = bankType == null ? null : bankType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_ORDER_HISTORY.COUPON_NO
     *
     * @return the value of UCARD_PAY_ORDER_HISTORY.COUPON_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getCouponNo() {
        return couponNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_ORDER_HISTORY.COUPON_NO
     *
     * @param couponNo the value for UCARD_PAY_ORDER_HISTORY.COUPON_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setCouponNo(String couponNo) {
        this.couponNo = couponNo == null ? null : couponNo.trim();
    }
}