package com.test.model;

import java.util.Date;

public class PaySysUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_SYS_USER.ID
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_SYS_USER.LOGIN_NAME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_SYS_USER.PASS_WORD
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String passWord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_SYS_USER.USER_NAME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_SYS_USER.STATUS
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_SYS_USER.GENDER
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_SYS_USER.TEL_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String telNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_SYS_USER.EMAIL_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private String emailNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_SYS_USER.CREATE_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UCARD_PAY_SYS_USER.UPDATE_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_SYS_USER.ID
     *
     * @return the value of UCARD_PAY_SYS_USER.ID
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_SYS_USER.ID
     *
     * @param id the value for UCARD_PAY_SYS_USER.ID
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_SYS_USER.LOGIN_NAME
     *
     * @return the value of UCARD_PAY_SYS_USER.LOGIN_NAME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_SYS_USER.LOGIN_NAME
     *
     * @param loginName the value for UCARD_PAY_SYS_USER.LOGIN_NAME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_SYS_USER.PASS_WORD
     *
     * @return the value of UCARD_PAY_SYS_USER.PASS_WORD
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_SYS_USER.PASS_WORD
     *
     * @param passWord the value for UCARD_PAY_SYS_USER.PASS_WORD
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord == null ? null : passWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_SYS_USER.USER_NAME
     *
     * @return the value of UCARD_PAY_SYS_USER.USER_NAME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_SYS_USER.USER_NAME
     *
     * @param userName the value for UCARD_PAY_SYS_USER.USER_NAME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_SYS_USER.STATUS
     *
     * @return the value of UCARD_PAY_SYS_USER.STATUS
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_SYS_USER.STATUS
     *
     * @param status the value for UCARD_PAY_SYS_USER.STATUS
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_SYS_USER.GENDER
     *
     * @return the value of UCARD_PAY_SYS_USER.GENDER
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_SYS_USER.GENDER
     *
     * @param gender the value for UCARD_PAY_SYS_USER.GENDER
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_SYS_USER.TEL_NO
     *
     * @return the value of UCARD_PAY_SYS_USER.TEL_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_SYS_USER.TEL_NO
     *
     * @param telNo the value for UCARD_PAY_SYS_USER.TEL_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo == null ? null : telNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_SYS_USER.EMAIL_NO
     *
     * @return the value of UCARD_PAY_SYS_USER.EMAIL_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public String getEmailNo() {
        return emailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_SYS_USER.EMAIL_NO
     *
     * @param emailNo the value for UCARD_PAY_SYS_USER.EMAIL_NO
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setEmailNo(String emailNo) {
        this.emailNo = emailNo == null ? null : emailNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_SYS_USER.CREATE_TIME
     *
     * @return the value of UCARD_PAY_SYS_USER.CREATE_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_SYS_USER.CREATE_TIME
     *
     * @param createTime the value for UCARD_PAY_SYS_USER.CREATE_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UCARD_PAY_SYS_USER.UPDATE_TIME
     *
     * @return the value of UCARD_PAY_SYS_USER.UPDATE_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UCARD_PAY_SYS_USER.UPDATE_TIME
     *
     * @param updateTime the value for UCARD_PAY_SYS_USER.UPDATE_TIME
     *
     * @mbg.generated Mon May 21 16:25:25 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}